exp_name: "cleaned"
exp: 'EBMLnew'
dataset:
  name: "sinusoids"
  include_lines: False
  num_ways: 1
  num_support: 5
  num_query: 10
  num_tasks: 500
  varying_shot: True  # for training only
train:
  meta_batch_size: 50
  max_epoch: 4000
  save_freq: 100
  val_freq: 100
model:
  num_phi_samples: 1
  latent_dim: 2
  hid_dim: 128
  decoder_sn: False
  encoder_sn: False
  prior_sn: False
  gaussian_decoder: True
  deterministic_phi: True
loss:
  kl_weight: 0.05
  ebmprior_weight: 0.1
  l2_weight: 0.1  # 1.0 for sampling in xy
  contrastive_loss: False
sgld:
  decoder:
    step: 0.001
    eta: 0.0001
    T: 1.0
    grad_clip: False
    niter: 20
    init: "noise"
    over_sample_ratio: 16
    sample_x: True
    clip_grad: -1
  prior:
    step: 0.001
    T: 0.0005
    grad_clip: False
    niter: 20
    eta: 0.005  # rsampling in xy, # 0.01 for y and 0.005 for x
    init: "buffer" # noise for sampling in xy
    over_sample_ratio: 1
    sample_in_xy: False
    sample_x: True
    clip_grad: -1
optimizer:
  lr: 0.0005
  beta1: 0.9
  beta2: 0.999






